# Generated by Django 5.1.2 on 2024-12-14 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_maincategory_shoppingcategory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="todo.category"
            ),
        ),
        migrations.RemoveField(
            model_name="todoitem",
            name="shopping_category",
        ),
        migrations.AddField(
            model_name="todoitem",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name="MainCategory",
        ),
        migrations.DeleteModel(
            name="ShoppingCategory",
        ),
    ]
