# Generated by Django 5.0.6 on 2024-05-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todoitem_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
