# Generated by Django 5.1 on 2024-09-04 01:36

import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todoitem_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='store',
            field=models.ForeignKey(default=django.db.models.query.QuerySet.first, on_delete=django.db.models.deletion.CASCADE, to='todo.store'),
        ),
    ]
