# Generated by Django 5.0.6 on 2024-05-24 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todoitem_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='name',
            field=models.CharField(default=datetime.datetime(2024, 5, 24, 15, 33, 23, 639410, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
