# Generated by Django 5.1 on 2024-09-04 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todoitem_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.store'),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
