# Generated by Django 5.1.2 on 2024-12-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0005_alter_todoitem_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitem",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
