# Generated by Django 5.1 on 2024-09-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_todoitem_store_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
