# Generated by Django 5.1.2 on 2024-12-18 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0007_shoppingcategory_alter_todoitem_quantity_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppingitem",
            name="shopping_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="todo.shoppingcategory",
            ),
        ),
    ]
