# Generated by Django 5.1.2 on 2024-12-18 14:19

import django.db.models.deletion
import todo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0008_shoppingitem_shopping_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingitem",
            name="category",
            field=models.ForeignKey(
                default=todo.models.Category.default_category,
                on_delete=django.db.models.deletion.CASCADE,
                to="todo.category",
            ),
        ),
    ]
