# Generated by Django 5.1.2 on 2024-12-18 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0009_alter_shoppingitem_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="todo.category",
            ),
        ),
    ]
