# Generated by Django 5.1.2 on 2024-12-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0010_alter_shoppingitem_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
