# Generated by Django 5.0.6 on 2024-06-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_todoitem_user_alter_todoitem_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='priority',
            field=models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('high', 'まじ高め'), ('high', '最速でやれよ')], default='medium', max_length=50),
        ),
    ]
