# Generated by Django 5.1.2 on 2024-12-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0011_deck"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="deck_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
