# Generated by Django 5.0.6 on 2024-06-26 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_alter_todoitem_priority_alter_todoitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='user',
        ),
    ]
