# Generated by Django 5.0.6 on 2024-07-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_alter_category_name_alter_todoitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='is_shopping',
            field=models.BooleanField(default=False),
        ),
    ]
