# Generated by Django 5.0.6 on 2024-07-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0017_todoitem_is_shopping'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='source',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
