# Generated by Django 5.0.6 on 2024-07-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0018_todoitem_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('prices', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
