# Generated by Django 5.0.6 on 2024-07-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0019_shoppingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='display_on_list',
            field=models.BooleanField(default=True),
        ),
    ]
